//
// Generated file, do not edit! Created by opp_msgtool 6.0 from src/UAVMessages.msg.
//

#ifndef __UAVMESSAGES_M_H
#define __UAVMESSAGES_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class UAVMessage;
class AckMessage;
class TimeoutMsg;
/**
 * Enum generated from <tt>src/UAVMessages.msg:6</tt> by opp_msgtool.
 * <pre>
 * // Enumeration for message priorities
 * enum MessagePriority
 * {
 *     LOW = 0;
 *     MEDIUM = 1;
 *     HIGH = 2;
 *     CRITICAL = 3;
 * }
 * </pre>
 */
enum MessagePriority {
    LOW = 0,
    MEDIUM = 1,
    HIGH = 2,
    CRITICAL = 3
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MessagePriority& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MessagePriority& e) { int n; b->unpack(n); e = static_cast<MessagePriority>(n); }

/**
 * Enum generated from <tt>src/UAVMessages.msg:15</tt> by opp_msgtool.
 * <pre>
 * // Enumeration for message types
 * enum MessageType
 * {
 *     DATA = 0;
 *     ACK = 1;
 *     NACK = 2;
 *     HEARTBEAT = 3;
 *     COMMAND = 4;
 * }
 * </pre>
 */
enum MessageType {
    DATA = 0,
    ACK = 1,
    NACK = 2,
    HEARTBEAT = 3,
    COMMAND = 4
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MessageType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MessageType& e) { int n; b->unpack(n); e = static_cast<MessageType>(n); }

/**
 * Class generated from <tt>src/UAVMessages.msg:25</tt> by opp_msgtool.
 * <pre>
 * // Base message class for UAV communications
 * message UAVMessage
 * {
 *     int sourceId;           // UAV or Ground Station ID
 *     int destId;             // Destination ID
 *     int sequenceNumber;     // For tracking and acknowledgment
 *     MessageType msgType;    // Type of message
 *     MessagePriority priority; // Priority level
 *     simtime_t timestamp;    // When message was created
 *     string payload;         // Actual data content (encrypted)
 *     double xPos;            // Position information
 *     double yPos;
 *     double zPos;
 *     double ndviValue;       // Normalized Difference Vegetation Index (Simulated)
 * }
 * </pre>
 */
class UAVMessage : public ::omnetpp::cMessage
{
  protected:
    int sourceId = 0;
    int destId = 0;
    int sequenceNumber = 0;
    MessageType msgType = static_cast<MessageType>(-1);
    MessagePriority priority = static_cast<MessagePriority>(-1);
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;
    omnetpp::opp_string payload;
    double xPos = 0;
    double yPos = 0;
    double zPos = 0;
    double ndviValue = 0;

  private:
    void copy(const UAVMessage& other);

  protected:
    bool operator==(const UAVMessage&) = delete;

  public:
    UAVMessage(const char *name=nullptr, short kind=0);
    UAVMessage(const UAVMessage& other);
    virtual ~UAVMessage();
    UAVMessage& operator=(const UAVMessage& other);
    virtual UAVMessage *dup() const override {return new UAVMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSourceId() const;
    virtual void setSourceId(int sourceId);

    virtual int getDestId() const;
    virtual void setDestId(int destId);

    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);

    virtual MessageType getMsgType() const;
    virtual void setMsgType(MessageType msgType);

    virtual MessagePriority getPriority() const;
    virtual void setPriority(MessagePriority priority);

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);

    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);

    virtual double getXPos() const;
    virtual void setXPos(double xPos);

    virtual double getYPos() const;
    virtual void setYPos(double yPos);

    virtual double getZPos() const;
    virtual void setZPos(double zPos);

    virtual double getNdviValue() const;
    virtual void setNdviValue(double ndviValue);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const UAVMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, UAVMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/UAVMessages.msg:41</tt> by opp_msgtool.
 * <pre>
 * // Acknowledgment message
 * message AckMessage extends UAVMessage
 * {
 *     int ackedSeqNum;        // Sequence number being acknowledged
 *     bool success;           // Whether operation was successful
 * }
 * </pre>
 */
class AckMessage : public ::UAVMessage
{
  protected:
    int ackedSeqNum = 0;
    bool success = false;

  private:
    void copy(const AckMessage& other);

  protected:
    bool operator==(const AckMessage&) = delete;

  public:
    AckMessage(const char *name=nullptr, short kind=0);
    AckMessage(const AckMessage& other);
    virtual ~AckMessage();
    AckMessage& operator=(const AckMessage& other);
    virtual AckMessage *dup() const override {return new AckMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getAckedSeqNum() const;
    virtual void setAckedSeqNum(int ackedSeqNum);

    virtual bool getSuccess() const;
    virtual void setSuccess(bool success);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AckMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AckMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/UAVMessages.msg:48</tt> by opp_msgtool.
 * <pre>
 * // Timeout self-message for retransmission
 * message TimeoutMsg extends cMessage
 * {
 *     int sequenceNumber;
 *     int retryCount;
 * }
 * </pre>
 */
class TimeoutMsg : public ::omnetpp::cMessage
{
  protected:
    int sequenceNumber = 0;
    int retryCount = 0;

  private:
    void copy(const TimeoutMsg& other);

  protected:
    bool operator==(const TimeoutMsg&) = delete;

  public:
    TimeoutMsg(const char *name=nullptr, short kind=0);
    TimeoutMsg(const TimeoutMsg& other);
    virtual ~TimeoutMsg();
    TimeoutMsg& operator=(const TimeoutMsg& other);
    virtual TimeoutMsg *dup() const override {return new TimeoutMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);

    virtual int getRetryCount() const;
    virtual void setRetryCount(int retryCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TimeoutMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TimeoutMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline UAVMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<UAVMessage*>(ptr.get<cObject>()); }
template<> inline AckMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<AckMessage*>(ptr.get<cObject>()); }
template<> inline TimeoutMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<TimeoutMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __UAVMESSAGES_M_H

